import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
export const metadata = {
  title: "Home || UOMO Ecommerce",
  description: "Generated by create next app",
}
export default function Mainlayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
